### ISSUE TITLE
Usage can be more elaborate

### ISSUE THREAD

**Issue by mithuns** [lukespragg/jalopy-maven-plugin#2]
Hi, 

I am intending to use this, but the Usage section in the Readme, is not very descriptive, 
neither is there a list of all goals that this plugin supports, (More like a feature-list, that would be great to see all capabilities offered by this) 
what goals to include in build, or any of that ? 
Just by adding the dependency , would that trigger jalopy execution ?

**Comment by lukespragg** [comment]
This is a fork of the original version and isn’t really maintained anymore.

**Comment by mithuns** [comment]
Can you please give me the link for that ?

**Comment by mithuns** [comment]
We can close this issue.
